version: '3.1'

services:

  covidcert_transformation_db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: covidcert
      POSTGRES_DB: covidcert
      POSTGRES_USER: covidcert
    ports:
      - "5434:5432"
    volumes:
      - covidcert_transformation_db_data:/var/lib/postgresql/data
volumes:
  covidcert_transformation_db_data:
